name: Deploy via FTP Locaweb

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Gerar build
        run: npm run build

      - name: FTP Deploy Locaweb
        uses: locaweb/ftp-deploy@1.0.0
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USER }}
          password: ${{ secrets.PASS }}
          localDir: "dist"